---
source: src/validation/tests/array_validation_test.rs
expression: res
---
SemanticError { message: "Array __main_arr_a_invalid has a size of 10 but 11 elements were provided", range: [SourceRange { range: 250..285 }], err_no: arr__invalid_array_assignment }
SemanticError { message: "Array __main_arr_b_invalid has a size of 10 but 11 elements were provided", range: [SourceRange { range: 441..480 }], err_no: arr__invalid_array_assignment }
SemanticError { message: "Array arr_a has a size of 10 but 11 elements were provided", range: [SourceRange { range: 828..863 }], err_no: arr__invalid_array_assignment }
SemanticError { message: "Array arr_a has a size of 10 but 11 elements were provided", range: [SourceRange { range: 878..911 }], err_no: arr__invalid_array_assignment }
SemanticError { message: "Array arr_b has a size of 10 but 11 elements were provided", range: [SourceRange { range: 926..965 }], err_no: arr__invalid_array_assignment }

